development:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: ripple_dev
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: ripple_test
  pool:     5

production:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: ripple_prod
  pool:     5
